### ISSUE TITLE
Deno compat/bypass for Jiti

### ISSUE THREAD

**Issue by birkskyum** [unjs/jiti#168]
### Environment

Similar to bun here 
- https://github.com/unjs/jiti/pull/156
- #154 

It would be great to have a bypass for Deno.

### Reproduction

Repro here
- https://github.com/denoland/deno/issues/20607
- https://github.com/denoland/deno/issues/20606

### Describe the bug

Jiti should not try to compile typescript when using Deno

**Comment by birkskyum** [comment]
Good question. Actually, I believe it's actually more picky. It does support CJS modules, but if I understand the announcement made  only when they are used inside dependencies imported through a `npm:` specifier.

**Comment by pi0** [comment]
Surely! We might also use a deno-specific ast transformer to handle necessary transformations (add extension, remap modules, etc) if that's what is needed on jiti side I'm totally up to it (only is a pitty because this way, Deno usage will be slower but i respect all reasons Deno runtime chose to keep stricter with ESM standards and disallow mixed syntaxes)

**Comment by pi0** [comment]
We have introduced new `jiti/native` subpath that always uses native `import` (tested against Deno 1.x).

Also made bun option generic to `tryNative` (https://github.com/unjs/jiti/pull/295) for main subpath export. Deno 1.x at least had some issues when i tested today. I think perhaps it is best that we let opting in into native-bypass for users/libs that use jiti (hopefully Deno 2.x will be better)
