### ISSUE TITLE
Typescript: Add support for class properties and emitDecoratorMetadata

### ISSUE THREAD

**Issue by sreuss** [unjs/jiti#57]
Hello,

switching Typescript transpilation to `jiti` in Nuxt 2.15.0 has caused some problems with our code base that have prevented us from upgrading:

We are using `class-validator` to validate data and define our classes like this:
```typescript
export class SomeModel {
  @IsString()
  @IsDefined()
  public readonly someField!: string;
}
```
This causes an `Error: TRANSFORM_ERROR: Definitely assigned fields cannot be initialized here, but only in the  constructor` on Nuxt startup which can be fixed by adding `@babel/plugin-proposal-class-properties` to the transformation. Somehow, `@babel/plugin-syntax-class-properties` is already included.

In addition, we are using Nest for our `serverMiddleware` and have some way to utilize it's dependency injection during server side rendering. Since the dependency injection relies on `emitDecoratorMetadata` we'd need `babel-plugin-transform-typescript-metadata` to be added to the transformation.

**Comment by cshomo11** [comment]
I am also seeing issues trying to use `json2typescript` on a model in a Nuxt servermiddleware. I specifically see the error about using `proposal-class-properties`.

` ERROR  Decorating class property failed. Please ensure that proposal-class-properties is enabled and runs after the decorators transform.`

**Comment by pi0** [comment]
Consdiering you already imported `IsString` and `IsDefined` this syntax works:

```js
export class SomeModel {
  @IsString()
  @IsDefined()
  public readonly someField: string;

  constructor(someField: string) {
    this.someField = someField;
  }
}
```

We also improved decorator meta support for v2.

**Comment by octet-stream** [comment]
@pi0 I'm still having this problem on v2.4.2, so I don't think this solves the issue. It's pretty common to use the `!` operator in TS classes to mark properties that will be assigned later. For example: This is how you would define entities in Mikro ORM. See examples from their docs: https://mikro-orm.io/docs/guide/first-entity#first-entity

It works with TSC, works with SWC, and works with tsx, and this needs proper fix in jiti. This issue blocks me from integrating Mikro ORM with jiti, because it will cause too many problems for developers who use this library.
